### ISSUE TITLE
Filename given to user actions should include full path, instead of relative to pi-timolo

### ISSUE THREAD

**Issue by surak** [pageauc/pi-timolo#112]
That is because if one starts pi-timolo from outside of its own directory, the location will be incorrect.

**Comment by pageauc** [comment]
pi-timolo config.py can use a relative or full os path.  The default is to use a relative path to the ./media folder.  You can override this behavior in the config.py to be any relative or fixed path you like.  Please note pi-timolo will attempt to create or complete the directory path if it does not exist.  Make sure there is not a file named the same as directory item in the path or you will get an OS error. 
Pi timolo can be moved to another folder name/location.  You may have to change to some shell scripts like pi-timolo.sh since they use full paths.  This could be changed to relative path but running script as a background daemon I believe works best with a full path.  I often run pi-timolo completely on a hard drive mount point so a small SD card can be used.  That is when you would need to change the pi-timolo.sh and webserver.sh scripts to reflect the new location.
Does this answer your question.
Claude ...
