### ISSUE TITLE
Dependency on pyexiv2

### ISSUE THREAD

**Issue by trunksio** [pageauc/pi-timolo#44]
There seems to be a dependency on pyexiv2 which no longer has a pip install option? 

sudo pip install pyexiv2
Downloading/unpacking pyexiv2
Could not find any downloads that satisfy the requirement pyexiv2
Cleaning up...
No distributions at all found for pyexiv2

or am I missing something in the setup. 
raspberry pi zero: raspbian 8 jessie

**Comment by pageauc** [comment]
Dependency is installed as part of  https://github.com/pageauc/pi-timolo/blob/master/source/pi-timolo-install.sh line 109
sudo apt-get install -yq python-picamera python-imaging dos2unix python-pyexiv2 libav-tools

Just tried
sudo apt-get install python-pyexiv2

This works so not sure where the error is coming from.  I do not do a pip install in the script

This library is just used to transfer image exif data when the image text is put on an image otherwise that meta data would be lost..  

Please provide more information on how to reproduce your problem and let me know

Claude ...

**Comment by trunksio** [comment]
For some reason that library did not get installed in the initial install script. 
I have run the apt-get install and it is working fine now- thanks!
