### ISSUE TITLE
How do I use the ip camera? 

### ISSUE THREAD

**Issue by biencuong** [pageauc/pi-timolo#68]
How do I use the ip camera? Please guide me!

**Comment by pageauc** [comment]
Do you mean pi-camera? or something else like an internet protocol camera.  Not sure what the question is.  
The raspberry pi camera is the default that pi-timolo uses, but you would need one installed.  Make sure the pi-camera is enabled from the raspi-config utility per https://www.raspberrypi.org/documentation/configuration/camera.md

Also the default setting for motion is motionTrackQuickPic = True that takes a smaller image from the video stream.  You can set motionTrackQuickPic = False and the pi-camera will take a regular non stream image but there will be a delay due to the time for the camera to warm up.

There is more information in the github wiki page here https://github.com/pageauc/pi-timolo/wiki
Hope this helps.  A better explanation of your question would help.
