### ISSUE TITLE
Background process closes after first photo

### ISSUE THREAD

**Issue by ErikBavenstrand** [pageauc/pi-timolo#75]
When running the bash script from rc.local the script only executes once then stops. No image is saved and crontab did not change anything.

**Comment by pageauc** [comment]
Will it Run from command prompt with config.py verbose=True

    cd ~/pi-timolo
    ./pi-timolo.py

If it fails please send console error message(s).  Let me know what version of Raspbian you are running and RPI model.  Note pi-timolo.py has been tested and will run under all recent versions of Raspbian as long as the pi-camera firmware is current.  Also note you cannot run pi-timolo.py from both /etc/rc.local and crontab although you can run pi-timolo.sh from both since it checks if process is already running and will not try to rerun.

### Some trouble shooting suggestions

* Does raspberry pi camera run OK from raspistill when pi-timolo is not trying to run.  Make sure no other program is accessing the pi-camera since it cannot be shared.  Also verify that the pi-camera has been enabled from sudo raspi-config.  For more detail see https://thepihut.com/blogs/raspberry-pi-tutorials/16021420-how-to-install-use-the-raspberry-pi-camera
* Rerun github curl script to ensure it completed successfully.  Note any error messages. 
* Update firmware  per wiki https://github.com/pageauc/pi-timolo/wiki/How-to-Install-or-Upgrade#update-firmware-optional
* Also I have recently had one user who had to reburn raspbian image so that is something you could try.
* Make sure you are doing initial testing with good lighting conditions so you can test motion tracking.  Low light conditions will take longer for timelapse and will not work very well for motion tracking depending on lighting conditions.
* Check raspberry pi power supply to ensure it can handle power requirements.

FYI - I have added a basic trouble shooting section to the pi-timolo wiki   
https://github.com/pageauc/pi-timolo/wiki/Basic-Trouble-Shooting

Claude ...
