### ISSUE TITLE
Motion pictures not copied to recent folder when motionTrackQuickPic = True

### ISSUE THREAD

**Issue by NelsonPJ** [pageauc/pi-timolo#91]
I know that the "recent" folder doesn't get updated with motion capture files if MotionVideoOn = True, so it won't have to copy mp4 files.  But I also noticed when motionTrackQuickPic= True, the media/recent/motion folder doesn't get updated.  The function "saveRecent" does not get called - maybe this is for speed of motion capture?

Digging into the pi-timolo.py code, the "saveRecent" function is also not called if motionQuickTLOn and daymode  (again, probably for speed?)

Not necessarily a big deal - just something that confused me when trying out new motion capture options.

**Comment by pageauc** [comment]
I would appreciate if you would test release 10.95 that now uses symlinks for recent folders.  These are indicated with @ in browser webserver.  I have also added motion videos and quicktimelapse to recent.  Note there is an h264_work folder in pi-timolo that stores the h264 video files.  I will look at adding code to cleanup these.  Conversion from h264 to mp4 is now done directly using MP4BOX using a subprocess in pi-timolo rather than using a convid.sh subprocess.  This also creates the symlink.  There will be a logging delay for MP4Box since it will take a short while to convert so messages MP4Box message can appear later in logging sequence.

I have done quite a bit of testing and fixed a few symlink glitches but would greatly appreciate further testing.  You should do a menubox.sh UPGRADE since webserver also has some additional error checks for bad symlinks.

Thanks Claude ...
