### ISSUE TITLE
symlink ability lost for motion pictures, not timelapses?

### ISSUE THREAD

**Issue by blokdk** [pageauc/pi-timolo#97]
Dear Mr. Pageau, 
I have started playing around with pi-timolo and transfer the files with rsync because I was/am more familiar with that than rclone. After transferring a lot of files I noticed that the recent folder was getting symlinks for the timelapses but not for the motion files. I had a look at the function definition in pi-timolo.py but could not figure out why this is happening.

Can you shed your light on it, please?

pablok

**Comment by pageauc** [comment]
What is probably happening is that the file locations for the symlinks are no longer there if you moved files
This has happened to me when I tried renaming some folders.  Easiest way is to delete all the symlinks in the recent/motion folder.  Deleting symlinks will not delete the actual media/motion or media/timelapse image files in the folders.  To clear the recent/motion folder symlinks

    cd ~/pi-timolo/media/recent/motion
    rm *

Then restart pi-timolo.py   You should see new symlinks getting created.  Image files will still be in media/motion sub folders

**Note** you may need to clear media/recent/motion or timelapse symlink files if you are deleting destination files that symlinks point to.  This is a check on the web browser since it cannot display a symlink that does not have a destination file. 

Let me know progress
Regards Claude ...
